NNPDENS and NNPDEHan Integration from NeuralPDE.jl
SciML/HighDimPDE.jl pull request #32
Opened 2022-06-08 17:32 UTC by ashutosh-b-b

2022-06-09 09:06 UTC, vboussange requested changes
Hey, thanks a lot for the work! Looks like everything runs smoothly, but it would be great to a bit of documentation.

2022-06-09 09:06 UTC, vboussange commented on src/NNPDENS.jl
> +        if save_everystep
Similar comments to NNPDEHan.jl apply here.

2022-06-09 09:06 UTC, vboussange commented on src/NNPDENS.jl
> +        if save_everystep
Similar comments to NNPDEHan.jl apply here.

2022-06-09 10:24 UTC, ashutosh-b-b commented on src/NNPDEHan.jl
> +            sol = PIDESolution(X0, ts, losses, iters, u0(X0)[1], (u_low, u_high))
Hi! These basically provide upper and lower bounds to the solution, you can check more about it [here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3071506) . I forgot to push the `HighDimPDE.jl` and added a field.

2022-06-09 10:47 UTC, ashutosh-b-b commented on src/NNPDEHan.jl
> +NNPDEHan(u0,σᵀ∇u;opt=Flux.ADAM(0.1)) = NNPDEHan(u0,σᵀ∇u,opt)
[Here](https://www.pnas.org/doi/10.1073/pnas.1718942115)

2022-06-10 11:31 UTC, vboussange reviewed
Thanks for the clarification. I will add some documentation and push it to the main branch. Thanks again!

2022-06-10 11:32 UTC, merged